version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 127.0.0.1:9090:9090
        restart: always

    alertmanager-bot:
        image: metalmatze/alertmanager-bot:0.4.3
        env_file: .env    
        volumes:
            - ./data:/data
        command:
            - --alertmanager.url=http://alertmanager:9093
            - --log.level=info
            - --store=bolt
            - --bolt.path=/data/bot.db
        ports:
            - 127.0.0.1:8080:8080
        restart: always

    alertmanager:
        image: prom/alertmanager:v0.21.0
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        command:
            - --config.file=/etc/alertmanager/config.yml
        ports:
            - 127.0.0.1:9093:9093
        restart: always


    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 127.0.0.1:9100:9100
        restart: always

    blackbox-exporter:
        image: prom/blackbox-exporter
        volumes:
            - ./blackbox:/config
        command: --config.file=/config/blackbox.yml
        ports:
            - 127.0.0.1:9115:9115
        restart: always
      
    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana/:/var/lib/grafana/
        depends_on:
            - prometheus
        ports:
            - 127.0.0.1:3000:3000
        restart: always